/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_science09_apple_demo_JavaNative */

#ifndef _Included_com_science09_apple_demo_JavaNative
#define _Included_com_science09_apple_demo_JavaNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_science09_apple_demo_JavaNative
 * Method:    getInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_science09_apple_demo_JavaNative_getInt
  (JNIEnv *, jobject);

/*
 * Class:     com_science09_apple_demo_JavaNative
 * Method:    setId
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_science09_apple_demo_JavaNative_setId
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_science09_apple_demo_JavaNative
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_science09_apple_demo_JavaNative_getStringFromNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
